### ISSUE TITLE
How is activation quantized in MobiletNet-v2?

### ISSUE THREAD

**Issue by haichaoyu** [hpi-xnor/BMXNet-v2-examples#4]
Hi,

Thanks for the useful example models. I read mobilenet.py and do not find any QActivation layer. I wonder how activation is quantized in each conv layer.

Thanks

**Comment by Jopyth** [comment]
We have not used MobileNet as a binary network so far (and it would not work the way the code is right now). If you wish to do so, you would need to adapt the layers accordingly. You could use `nn.activated_conv` instead of the `QActivation` layer.
